using FabMatch.Domain.Common;

namespace FabMatch.Domain.Entities;

/// <summary>
/// Result of an AI analysis run on a <see cref="Plan"/>.
/// Captures the identified manufacturing process, cost estimates and raw AI output.
/// </summary>
public sealed class Analysis : BaseEntity
{
    // ── Relations ──────────────────────────────────────────────────

    /// <summary>FK to the analysed plan.</summary>
    public Guid PlanId { get; private set; }

    /// <summary>Navigation to the analysed plan.</summary>
    public Plan Plan { get; private set; } = null!;

    // ── AI output ──────────────────────────────────────────────────

    /// <summary>Manufacturing processes identified (e.g. ["Laser Cutting", "Bending"]).</summary>
    public List<string> IdentifiedProcesses { get; private set; } = [];

    /// <summary>Materials detected in the drawing.</summary>
    public List<string> IdentifiedMaterials { get; private set; } = [];

    /// <summary>Estimated manufacturing cost in the project's currency.</summary>
    public decimal? EstimatedManufacturingCost { get; private set; }

    /// <summary>Estimated selling price (manufacturing cost + margin).</summary>
    public decimal? EstimatedSellingPrice { get; private set; }

    /// <summary>Currency used for cost/price estimates (ISO 4217).</summary>
    public string Currency { get; private set; } = "EUR";

    /// <summary>Estimated production time in working days.</summary>
    public int? EstimatedDurationDays { get; private set; }

    /// <summary>Overall AI confidence score between 0 and 1.</summary>
    public double ConfidenceScore { get; private set; }

    /// <summary>Raw JSON summary returned by the AI provider.</summary>
    public string? RawAiResponse { get; private set; }

    /// <summary>Human-readable summary generated by AI.</summary>
    public string? Summary { get; private set; }

    /// <summary>Name of the AI model/provider used.</summary>
    public string AIProvider { get; private set; } = string.Empty;

    // ── Factory ────────────────────────────────────────────────────

    /// <summary>Creates a new analysis result.</summary>
    public static Analysis Create(
        Guid planId,
        List<string> identifiedProcesses,
        List<string> identifiedMaterials,
        decimal? estimatedManufacturingCost,
        decimal? estimatedSellingPrice,
        string currency,
        int? estimatedDurationDays,
        double confidenceScore,
        string? rawAiResponse,
        string? summary,
        string aiProvider)
    {
        return new Analysis
        {
            PlanId = planId,
            IdentifiedProcesses = identifiedProcesses,
            IdentifiedMaterials = identifiedMaterials,
            EstimatedManufacturingCost = estimatedManufacturingCost,
            EstimatedSellingPrice = estimatedSellingPrice,
            Currency = currency,
            EstimatedDurationDays = estimatedDurationDays,
            ConfidenceScore = confidenceScore,
            RawAiResponse = rawAiResponse,
            Summary = summary,
            AIProvider = aiProvider
        };
    }
}
