using FabMatch.Domain.Common;
using FabMatch.Domain.Enums;

namespace FabMatch.Domain.Entities;

/// <summary>
/// A manufacturing project created by a <see cref="Client"/>.
/// Contains one or more <see cref="Plan"/> documents that are analysed by AI
/// to generate match proposals with suitable suppliers.
/// </summary>
public sealed class Project : BaseEntity
{
    // ── Relations ──────────────────────────────────────────────────

    /// <summary>FK to the owning client profile.</summary>
    public Guid ClientId { get; private set; }

    /// <summary>Navigation to the owning client.</summary>
    public Client Client { get; private set; } = null!;

    // ── Project metadata ───────────────────────────────────────────

    /// <summary>Short human-readable title (e.g. "Chassis bracket – series 50").</summary>
    public string Title { get; private set; } = string.Empty;

    /// <summary>Detailed description of the manufacturing requirement.</summary>
    public string Description { get; private set; } = string.Empty;

    /// <summary>Current lifecycle state.</summary>
    public ProjectStatus Status { get; private set; } = ProjectStatus.Draft;

    /// <summary>Whether the project is visible to all suppliers on the platform.</summary>
    public bool IsPublic { get; private set; }

    // ── Shared project properties ──────────────────────────────────

    /// <summary>Target delivery date requested by the client.</summary>
    public DateTime? DeliveryDate { get; private set; }

    /// <summary>
    /// Estimated budget for the project (used as a matching signal).
    /// </summary>
    public decimal? BudgetEstimate { get; private set; }

    /// <summary>Currency of the budget estimate (ISO 4217, default "EUR").</summary>
    public string BudgetCurrency { get; private set; } = "EUR";

    /// <summary>List of required manufacturing processes (e.g. ["Laser Cutting","Bending"]).</summary>
    public List<string> RequiredProcesses { get; private set; } = [];

    /// <summary>List of materials specified (e.g. ["S235JR", "Aluminium 5754"]).</summary>
    public List<string> Materials { get; private set; } = [];

    /// <summary>
    /// AI-generated embedding vector of the project's technical requirements.
    /// Used for cosine-similarity matching against supplier embeddings.
    /// </summary>
    public float[]? EmbeddingVector { get; private set; }

    // ── Navigation properties ──────────────────────────────────────

    /// <summary>Plans (drawings / blueprints) attached to this project.</summary>
    public ICollection<Plan> Plans { get; private set; } = [];

    /// <summary>Match proposals generated by AI for this project.</summary>
    public ICollection<Match> Matches { get; private set; } = [];

    // ── Factory / state-machine ────────────────────────────────────

    /// <summary>Creates a new draft project.</summary>
    public static Project Create(
        Guid clientId,
        string title,
        string description,
        bool isPublic = false,
        DateTime? deliveryDate = null,
        decimal? budgetEstimate = null,
        string budgetCurrency = "EUR")
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(title);
        return new Project
        {
            ClientId = clientId,
            Title = title,
            Description = description,
            IsPublic = isPublic,
            DeliveryDate = deliveryDate,
            BudgetEstimate = budgetEstimate,
            BudgetCurrency = budgetCurrency
        };
    }

    /// <summary>Updates mutable project properties.</summary>
    public void Update(
        string title,
        string description,
        bool isPublic,
        DateTime? deliveryDate,
        decimal? budgetEstimate,
        string budgetCurrency,
        List<string>? requiredProcesses,
        List<string>? materials)
    {
        Title = title;
        Description = description;
        IsPublic = isPublic;
        DeliveryDate = deliveryDate;
        BudgetEstimate = budgetEstimate;
        BudgetCurrency = budgetCurrency;
        RequiredProcesses = requiredProcesses ?? [];
        Materials = materials ?? [];
        Touch();
    }

    /// <summary>Publishes the project (transitions from Draft → Active).</summary>
    /// <exception cref="InvalidOperationException">If the project has no plans.</exception>
    public void Publish()
    {
        if (!Plans.Any())
            throw new InvalidOperationException("Cannot publish a project with no plans.");
        Status = ProjectStatus.Active;
        Touch();
    }

    /// <summary>Marks the project as cancelled.</summary>
    public void Cancel()
    {
        Status = ProjectStatus.Cancelled;
        Touch();
    }

    /// <summary>Transitions to InNegotiation when a supplier is selected.</summary>
    public void StartNegotiation()
    {
        Status = ProjectStatus.InNegotiation;
        Touch();
    }

    /// <summary>Marks the project as awarded (contract signed).</summary>
    public void Award()
    {
        Status = ProjectStatus.Awarded;
        Touch();
    }

    /// <summary>Marks the project as completed.</summary>
    public void Complete()
    {
        Status = ProjectStatus.Completed;
        Touch();
    }

    /// <summary>Stores the AI embedding vector for semantic matching.</summary>
    public void SetEmbedding(float[] vector)
    {
        EmbeddingVector = vector;
        Touch();
    }
}
